
version: 2

models:
  - name: my_first_dbt_model
    description: "My first dbt model"
    columns:
      - name: id
        description: "The primary key for first table."
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "Second dbt model"
    columns:
      - name: id
        description: "The primary key for my second table. fix5"
        data_tests:
          - unique
          - not_null
